### ISSUE TITLE
server error morgan@spf15.info

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/app-material-fair-com#27]
"user is getting an internal server error when trying to save"

user email: morgan@spf15.info

related kadira errors:
https://ui.kadira.io/et/382b6921-eafd-48e0-8fc5-06bc09c51268
https://ui.kadira.io/et/1573c680-5e14-4607-8da9-f6621a9b55f0

**Comment by mixcas** [comment]
i don't think incorrect password is related
