### ISSUE TITLE
Conekta double charge

### ISSUE THREAD

**Issue by varffs** [interglobalvision/app-material-fair-com#30]
Brett says 'seems' this is happening. Needs confirmation this is a real bug

**Comment by mixcas** [comment]
There's duplicated payments on the Conekta dashboard. I would say it's happening.

**Comment by mikeyrayvon** [comment]
does the `submit

**Comment by mikeyrayvon** [comment]
does the `submit` button successfully disable on-click until a reply is received from conekta?

**Comment by mixcas** [comment]
So there was two Charges for that user because of #30, first one went thru well, second one was declined by the bank security.
